/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Promo } from "./Promo";
import { PromoCountArgs } from "./PromoCountArgs";
import { PromoFindManyArgs } from "./PromoFindManyArgs";
import { PromoFindUniqueArgs } from "./PromoFindUniqueArgs";
import { DeletePromoArgs } from "./DeletePromoArgs";
import { PromoService } from "../promo.service";
@graphql.Resolver(() => Promo)
export class PromoResolverBase {
  constructor(protected readonly service: PromoService) {}

  async _promosMeta(
    @graphql.Args() args: PromoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Promo])
  async promos(@graphql.Args() args: PromoFindManyArgs): Promise<Promo[]> {
    return this.service.promos(args);
  }

  @graphql.Query(() => Promo, { nullable: true })
  async promo(
    @graphql.Args() args: PromoFindUniqueArgs
  ): Promise<Promo | null> {
    const result = await this.service.promo(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Promo)
  async deletePromo(
    @graphql.Args() args: DeletePromoArgs
  ): Promise<Promo | null> {
    try {
      return await this.service.deletePromo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
